name: Graphcore copyright header check
on:
  pull_request:
  push:
    branches: [master]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Run test_copyright.py
        run: python3 ../graphcore_cloud_tools/testing/test_copyright.py
